<?php $lang = (isset($_GET['lang']))? $_GET['lang'] : ""; ?>

<?php if($lang == "fr" ){?>
	<x><rs n="extrastuff" c="miscellaneous,cutscenes,characters,abouttitle,aboutcontent"><r><c n="miscellaneous"><![CDATA[Divers]]></c><c n="cutscenes"><![CDATA[Passages supprimés]]></c><c n="characters"><![CDATA[Personnages]]></c><c n="abouttitle"><![CDATA[À propos de...]]></c><c n="aboutcontent"><![CDATA[Voici quelques éléments tirés de mes notes qui vous intéresseront peut-être : des scènes coupées, des détails supplémentaires sur certains personnages et d'autres informations totalement inutiles que j'ai néanmoins décidé d'inclure. Attendez-vous à en voir apparaître d'autres : j'ai des tas de notes...]]></c></r></rs></x>
<?php } elseif($lang == "es" ){?>
	<x><rs n="extrastuff" c="miscellaneous,cutscenes,characters,abouttitle,aboutcontent"><r><c n="miscellaneous"><![CDATA[Varios]]></c><c n="cutscenes"><![CDATA[Fragmentos]]></c><c n="characters"><![CDATA[Personajes]]></c><c n="abouttitle"><![CDATA[Acerca de]]></c><c n="aboutcontent"><![CDATA[Aquí encontrarás algunas notas que tal vez te parezcan interesantes; algunas escenas que se eliminaron, algunos datos adicionales sobre los personajes e informaciones totalmente inútiles que por alguna razón me apeteció incluir para vosotros. Habrá muchas más: tengo montones de notas.]]></c></r></rs></x>
<?php } elseif($lang == "de" ){?>
	<x><rs n="extrastuff" c="miscellaneous,cutscenes,characters,abouttitle,aboutcontent"><r><c n="miscellaneous"><![CDATA[Dies und das]]></c><c n="cutscenes"><![CDATA[Weglassungen]]></c><c n="characters"><![CDATA[Charaktere]]></c><c n="abouttitle"><![CDATA[Info]]></c><c n="aboutcontent"><![CDATA[Hier seht ihr allerlei Bruchstücke aus meinen Notizen, die euch vielleicht interessieren könnten: einige Szenen, die herausgenommen wurden, ein paar zusätzliche Einzelheiten über die Charaktere und dazu noch völlig unnütze Informationen, die ich einfach so dazugetan habe. Von der Sorte gibt es später noch mehr, ich habe ja reichlich Notizen ...]]></c></r></rs></x>
<?php } elseif($lang == "it" ){?>
	<x><rs n="extrastuff" c="miscellaneous,cutscenes,characters,abouttitle,aboutcontent"><r><c n="miscellaneous"><![CDATA[Varie]]></c><c n="cutscenes"><![CDATA[Scene tagliate]]></c><c n="characters"><![CDATA[Personaggi]]></c><c n="abouttitle"><![CDATA[Info]]></c><c n="aboutcontent"><![CDATA[Ecco qui parti e frammenti dei miei appunti che potreste trovare interessanti; scene che sono state tagliate, un po' di dettagli extra su qualche personaggio e alcune informazioni del tutto inutili che ho pensato di mettere comunque nel mucchio. Ne arriveranno altre, ho un sacco di appunti.]]></c></r></rs></x>
<?php } else {?>
	<x><rs n="extrastuff" c="miscellaneous,cutscenes,characters,abouttitle,aboutcontent"><r><c n="miscellaneous"><![CDATA[Miscellaneous]]></c><c n="cutscenes"><![CDATA[Edits]]></c><c n="characters"><![CDATA[Characters]]></c><c n="abouttitle"><![CDATA[About]]></c><c n="aboutcontent"><![CDATA[Here are a few bits and pieces from my notes that you might find interesting; some scenes that were cut, a few extra details about some of the characters and some completely useless information that I thought I'd throw in anyway.  There will be more where this came from, I've got a lot of notes.]]></c></r></rs></x>
<?php } ?>