<x><rs n="extrastuff" c="ID,t,sp,c">
<?php
$ref = (isset($_GET['ref']))? $_GET['ref'] : ""; ?>

<?php if($ref == "characters" ){?>
<r><c n="ID"><![CDATA[10]]></c><c n="t"><![CDATA[Pattenrond]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[9]]></c><c n="t"><![CDATA[Gilderoy Lockhart]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[26]]></c><c n="t"><![CDATA[Harry et Dudley : y a-t-il un espoir ?]]></c><c n="sp"><![CDATA[1]]></c></r><r><c n="ID"><![CDATA[8]]></c><c n="t"><![CDATA[Hermione Granger]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[11]]></c><c n="t"><![CDATA[Nick Quasi-Sans-Tête]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[7]]></c><c n="t"><![CDATA[Informations diverses sur la famille Weasley]]></c><c n="sp"><![CDATA[0]]></c></r>
<?php } ?>

<?php if($ref == "cutscenes" ){?>
<r><c n="ID"><![CDATA[2]]></c><c n="t"><![CDATA[L'histoire de Dean Thomas (La chambre des secrets)]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="t"><![CDATA[Mafalda (La coupe de feu)]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[5]]></c><c n="t"><![CDATA[Malfoy & Nott (Chamber of Secrets/Goblet of Fire)]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[4]]></c><c n="t"><![CDATA[Mopsy, l'amie des chiens (La coupe de feu)]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="t"><![CDATA[Premiers chapitres de « L'école des sorciers »]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[6]]></c><c n="t"><![CDATA[Le premier chapitre du sixième roman]]></c><c n="sp"><![CDATA[0]]></c></r>
<?php } ?>

<?php if($ref == "miscellaneous" ){?>
<r><c n="ID"><![CDATA[22]]></c><c n="t"><![CDATA[Cela n'intéressera probablement que les filles...]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[12]]></c><c n="t"><![CDATA[Les Harry Potter]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[21]]></c><c n="t"><![CDATA[Ma rencontre avec Melissa et Emerson]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[13]]></c><c n="t"><![CDATA[Démineur]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[17]]></c><c n="t"><![CDATA[Dernières nouvelles du Démineur]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[23]]></c><c n="t"><![CDATA[QJP]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[20]]></c><c n="t"><![CDATA[Hiboux et chouettes]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="t"><![CDATA[Les endroits où écrire]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[24]]></c><c n="t"><![CDATA[Définitions de sorts]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="t"><![CDATA[CRACMOLS]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[25]]></c><c n="t"><![CDATA[La Baguette de Sureau]]></c><c n="sp"><![CDATA[1]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="t"><![CDATA[L'équipe d'Irlande de Quidditch et le club de football de West Ham]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[18]]></c><c n="t"><![CDATA[BAGUETTES]]></c><c n="sp"><![CDATA[0]]></c></r>
<?php } ?>
</rs></x>