<?php $lang = (isset($_GET['lang']))? $_GET['lang'] : ""; 
$website_version = (file_exists("../config.ini"))?(parse_ini_file("../config.ini")["website_version"]):"4"; ?>

<?php if($lang == "fr" ){?>
<x><rs n="fansites" c="ID,m,t,c,i,url,sp"><r><c n="ID"><![CDATA[20]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[The HP Alliance]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Harry Potter Fan Zone.com]]></c></r><r><c n="ID"><![CDATA[18]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[Potterish.com]]></c></r><r><c n="ID"><![CDATA[17]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Leaky Cauldron]]></c></r><r><c n="ID"><![CDATA[16]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[HPANA]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[MuggleNet]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[The Harry Potter Lexicon]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[Godric’s Hollow]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="m"><![CDATA[3]]></c><c n="t"><![CDATA[Immeritus]]></c></r></rs></x>
<?php } elseif($lang == "es" ){?>
<x><rs n="fansites" c="ID,m,t,c,i,url,sp"><r><c n="ID"><![CDATA[20]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[La Alianza HP]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Harry Potter Fan Zone.com]]></c></r><r><c n="ID"><![CDATA[18]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[Potterish.com]]></c></r><r><c n="ID"><![CDATA[17]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[El Caldero Chorreante]]></c></r><r><c n="ID"><![CDATA[16]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[HPANA]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[MuggleNet]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[The Harry Potter Lexicon]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[Godric's Hollow (el valle de Godric)]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="m"><![CDATA[3]]></c><c n="t"><![CDATA[Immeritus]]></c></r></rs></x>
<?php } elseif($lang == "de" ){?>
<x><rs n="fansites" c="ID,m,t,c,i,url,sp"><r><c n="ID"><![CDATA[20]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[Die HP Alliance]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Harry Potter Fan Zone.com]]></c></r><r><c n="ID"><![CDATA[18]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[Potterish.com]]></c></r><r><c n="ID"><![CDATA[17]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[The Leaky Cauldron]]></c></r><r><c n="ID"><![CDATA[16]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[HPANA]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[MuggleNet]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[The Harry Potter Lexicon]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[Godric’s Hollow]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="m"><![CDATA[3]]></c><c n="t"><![CDATA[Immeritus]]></c></r></rs></x>
<?php } elseif($lang == "it" ){?>
<x><rs n="fansites" c="ID,m,t,c,i,url,sp"><r><c n="ID"><![CDATA[20]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[La HP Alliance]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Harry Potter Fan Zone.com]]></c></r><r><c n="ID"><![CDATA[18]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[Potterish.com]]></c></r><r><c n="ID"><![CDATA[17]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Leaky Cauldron]]></c></r><r><c n="ID"><![CDATA[16]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[HPANA]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[MuggleNet]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[The Harry Potter Lexicon]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[Godric’s Hollow]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="m"><![CDATA[3]]></c><c n="t"><![CDATA[Immeritus]]></c></r></rs></x>
<?php } else {?>
<x><rs n="fansites" c="ID,m,t,c,i,url,sp">
	<?php if($website_version > 3 ){?>
<r><c n="ID"><![CDATA[20]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[The HP Alliance]]></c></r><r><c n="ID"><![CDATA[19]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[Harry Potter Fan Zone.com]]></c></r>
	<?php } if($website_version > 2 ){?>
<r><c n="ID"><![CDATA[18]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[Potterish.com]]></c></r>
	<?php } if($website_version > 1 ){?>
<r><c n="ID"><![CDATA[17]]></c><c n="m"><![CDATA[5]]></c><c n="t"><![CDATA[The Leaky Cauldron]]></c></r>
	<?php } if($website_version > 0 ){?>
<r><c n="ID"><![CDATA[16]]></c><c n="m"><![CDATA[12]]></c><c n="t"><![CDATA[HPANA]]></c></r><r><c n="ID"><![CDATA[15]]></c><c n="m"><![CDATA[9]]></c><c n="t"><![CDATA[MuggleNet]]></c></r><r><c n="ID"><![CDATA[14]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[The Harry Potter Lexicon]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="m"><![CDATA[6]]></c><c n="t"><![CDATA[Godric’s Hollow]]></c></r>
	<?php }?>
<r><c n="ID"><![CDATA[1]]></c><c n="m"><![CDATA[3]]></c><c n="t"><![CDATA[Immeritus]]></c></r></rs></x>
<?php } ?>