<?php $lang = (isset($_GET['lang']))? $_GET['lang'] : ""; 
$website_version = (file_exists("../config.ini"))?(parse_ini_file("../config.ini")["website_version"]):"4"; ?>

<?php if($lang == "fr" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[10]]></c><c n="a"><![CDATA[Jessica adore les livres, ce qui est très gentil de sa part dans la mesure où elle a dû me partager avec Harry pendant si longtemps. David ignore totalement qui est Harry Potter, ce qui fait de lui quelqu'un d'extrêmement reposant !]]></c></r>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[La même que celle qu'il a adoptée devant Molly Weasley lorsqu'elle en a laissé un sortir de l'armoire dans « L'Ordre du Phénix » : les êtres aimés que j'ai perdus. En revanche, si vous faites allusion à une peur tout à fait personnelle, ce serait d'être enterrée vivante. J'ignore comment ferait un épouvantard pour représenter cela ; peut-être en se transformant en cercueil autour de moi ? Argh...]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[J'ai dans mes tiroirs diverses choses auxquelles je pourrais me remettre, mais il est possible que j'écrive quelque chose de très différent. Je n'en sais vraiment rien.
]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[Comme vous le diront les fans les plus attentifs, il m'arrive de me tromper ! Certaines salles de cours changent mystérieusement d'étage d'un roman à l'autre, et ce ne sont que les fautes les plus bénignes de « raccord », comme on dit au cinéma... La plupart des sites de fans vous indiqueront où se trouvent mes étourderies. Mais l'essentiel demeure cohérent au fil des romans parce que l'intrigue globale est établie depuis fort longtemps et tout à fait claire dans mon esprit.
]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Cela peut aller de dix minutes (ce qui est le cas actuellement compte tenu de l'âge de mon bébé) à dix heures. J'adore écrire la nuit, mais cela m'est malheureusement impossible pour l'instant : je dois profiter de la moindre occasion de dormir !]]></c></r>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[Je n'ose pas révéler toute l'horreur de cette expérience, mais sachez qu'elle a eu lieu dans un pub d'Exeter (une ville de la côte sud de l'Angleterre où j'ai étudié à l'université) en 1984 et est liée à une plaisanterie de mon cru qui s'est retournée contre moi de manière spectaculaire. Ce désastre a eu pour témoin mon amie Pauline, que je mentionne ailleurs dans ce site (je dois perpétuellement lui faire plaisir pour éviter qu'elle ne raconte tout).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[Je suis très touchée que des gens se proposent, mais, à vrai dire, il n'y aurait pas grand-chose à faire ! Mon travail se limite à s'installer dans une pièce ou un café pour écrire et je n'ai pas besoin d'aide pour cela !]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[J'ai pas mal voyagé en Europe et je suis allée plusieurs fois aux États-Unis, mais essentiellement dans le cadre de voyages de promotion, ce qui signifie que j'ai vu beaucoup de chambres d'hôtel, de librairies et de plateaux de télévision avec, dans l'intervalle, quelques aperçus de paysages ou monuments célèbres. L'exception à la règle est New York, que j'ai visité comme une simple touriste et que j'adore. Je suis partie en safari en Afrique pour la première fois l'an dernier, ce qui fut loin d'être simple car David n'avait que cinq mois à l'époque, mais ce séjour a été vraiment merveilleux.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[Je crains que la réponse soit « non », même si vous avez pu apercevoir des Américains et personnages d'autres origines lors de la coupe du monde de Quidditch. La raison en est simple : j'écris sur la Grande-Bretagne et sur une école britannique et il n'existe aucune justification logique à l'introduction d'étrangers ; il est d'ailleurs probable que si j'utilisais de tels personnages, ils sonneraient faux. On me dit souvent ce que je devrais insérer dans les aventures de Harry Potter, mais ces histoires n'appartiennent qu'à moi. Et si quelqu'un veut écrire sur des sorciers américains, il est bien entendu libre de le faire...]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[Revenez pour le savoir !]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[Tout d'abord, écrivez quelque chose qu'un éditeur aimerait publier (il suffit d'un seul éditeur, mais le trouver prend parfois du temps ; si tous les éditeurs repoussent votre manuscrit, vous devrez envisager le fait que ce que vous avez écrit n'est pas publiable). Ensuite, vous devez prendre contact avec l'éditeur, soit directement, soit (ce qui est préférable si vous pouvez vous le permettre) par l'intermédiaire d'un agent qui agira pour votre compte. Le meilleur moyen de trouver les adresses des éditeurs et agents consiste à en dénicher un annuaire. Au Royaume-Uni, le plus connu est « The Writer's and Artist's Yearbook » ; pour les pays francophones, je pense qu'une recherche sur Internet utilisant les mots-clés « annuaire » et « éditeur » ou « agent » devrait vous fournir une première piste. Vérifiez par ailleurs que vous vous adressez à la bonne personne ou société : inutile d'expédier un manuscrit de science-fiction à un éditeur d'ouvrages médicaux... Attendez. Priez. C'est ainsi que Harry Potter a trouvé un éditeur.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[J'ai choisi quelques correspondants ces dernières années (même si je ne réponds pas toujours très vite lorsque je suis plongée dans l'écriture d'un roman !) ; cependant, pour être tout à fait franche, je ne pense pas avoir assez de temps pour entretenir des échanges avec de nouveaux correspondants. Jessica et David passent en premier : vous pouvez choisir parmi des millions de correspondants, mais mes enfants ne pouvant se choisir d'autre mère, ce sont eux qui ont le plus besoin de mon temps !]]></c></r>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Toujours... Dès que j'ai su ce qu'était un écrivain, j'ai voulu le devenir. J'ai le tempérament idéal pour devenir écrivain : je me sens parfaitement bien seule, dans une pièce, à inventer des choses.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Oui, beaucoup, mais rien d'autre n'a été édité (ce qui n'est pas une perte, croyez-moi). Mes premières « œuvres » furent les histoires de Lapin, qui racontaient les aventures d'un lapin appelé Lapin. J'avais alors entre six et huit ans. Puis, à onze ans, j'ai écrit un roman au sujet de sept diamants maudits et de leurs possesseurs. Depuis, j'ai énormément écrit : nouvelles, morceaux de romans pour adultes, toutes sortes de choses.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[J'ai été « assistante de recherche » pour Amnesty International pendant quelque temps, ce qui fut très intéressant même si je me demande si j'ai pu leur être d'une quelconque utilité compte tenu de mon manque d'organisation chronique (mon bureau en est la preuve en image). Mes plus longs postes, en dehors de l'écriture, ont touché à l'enseignement : j'ai enseigné le français en Écosse et l'anglais au Portugal.]]></c></r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[Ma possession matérielle préférée est notre maison dans le nord de l'Écosse : elle est très calme et nous y passons d'excellents moments avec notre famille et nos amis. Mais le changement le plus agréable qu'ont apporté les droits d'auteur à ma vie est probablement l'absence de souci matériel. Je n'ai pas oublié le sentiment que l'on ressent en se demandant si l'on va être en mesure de payer les factures. Ne plus avoir à s'en préoccuper est probablement plus grand luxe au monde.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[J'adore Harry, Hermione, Ron, Hagrid, Dumbledore, Ginny, Fred, George et Lupin. J'aime beaucoup écrire sur Rogue (même si je n'ai pas nécessairement envie de le rencontrer...). Mon nouveau personnage préféré est Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[Gryffondor, j'espère. J'apprécie énormément le courage.]]></c></r></rs></x>
<?php } elseif($lang == "es" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[10]]></c><c n="a"><![CDATA[A Jessica le encantan los libros, lo que es muy halagador, dado todo el tiempo que tuvo que compartirme con Harry. David aún no tiene ni idea de quién es Harry Potter, lo que resulta todo un descanso.]]></c></r>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[Lo mismo que vio Molly Weasley cuando dejó salir un boggart del armario cerrado en "La orden del Fénix": a mis seres queridos, muertos. Pero si te refieres a un temor personal, sería que me enterrasen viva. No estoy segura de cómo lo representaría el boggart: ¿tal vez convirtiéndose en un ataúd conmigo dentro? Urgh.]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[Hay varias cosas que languidecen en mis cajones que tal vez recupere, pero posiblemente escriba algo totalmente distinto. En realidad no lo sé.]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[Como podrán atestiguar los fans más obsesivos, sí que meto la pata a veces. Algunas aulas cambian misteriosamente de lugar entre los libros, ¡por mencionar sólo uno de los pequeños errores de continuidad! La mayoría de los sitios Web de los fans os indicarán mis errores. Pero la coherencia de los datos esenciales se mantiene entre los libros porque dediqué mucho tiempo a trazar la línea argumental principal, y la tengo siempre muy clara en la mente.
]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Entre diez minutos (¡el tiempo de que dispongo últimamente, con todo el trabajo que me da el bebé!) y diez horas. Me encanta escribir de noche, pero últimamente no me es posible: ¡tengo que aprovechar para dormir cuando puedo!]]></c></r>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[No sería capaz de revelar todo el horror del momento más embarazoso de mi vida, pero ocurrió en un pub de Exeter (una ciudad en la costa sur de Inglaterra en la que fui a la universidad) en 1984. Conté un chiste, pero me salió el tiro por la culata. Este desastre fue presenciado por mi amiga Pauline, quien aparece mencionada en otros lugares de este sitio (tengo que tenerla contenta para que NO HABLE demasiado).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[Es conmovedor que deseéis ayudarme de esta manera, ¡pero la verdad es que no hay mucho que hacer! Simplemente, me siento en una habitación o en una cafetería y escribo, ¡y para esto no necesito ninguna ayuda!]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[He recorrido buena parte de Europa, y he viajado a Estados Unidos varias veces, aunque sobre todo en giras de presentación de libros, lo que significa conocer habitaciones de hotel, librerías y estudios de televisión, con breves visitas a los principales puntos turísticos de cada ciudad. La excepción es Nueva York, que sí he visitado como persona normal, y que me encanta. El año pasado fui por primera vez a un safari en África, lo que constituyó todo un reto, ya que David sólo tenía cinco meses, pero me pareció maravilloso.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[Creo que la respuesta a esta pregunta es "no", aunque ya hemos visto algún personaje norteamericano y de otras nacionalidades en los Mundiales de quidditch. La razón es obvia: escribo sobre Gran Bretaña y una escuela británica, con lo que no hay razones lógicas para introducir personas extranjeras así porque sí: estoy segura de que resultaría gratuito. Me hacen muchas sugerencias sobre qué cosas debería incluir en los libros de Harry Potter, pero las historias son sólo mías; si alguien desea escribir sobre brujos norteamericanos, ¡que escriba su propio libro!]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[¡Estad atentos a este sitio!]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[En primer lugar hace falta escribir algo que pueda ser interesante para una editorial (sólo hace falta encontrar una, pero puede llevar tiempo. Si todas las editoriales rechazan tu libro, tendrás que considerar la posibilidad de que lo que has escrito no sea publicable). En segundo lugar, tienes que ponerte en contacto con el editor, ya sea directamente o (lo más recomendable si puedes permitírtelo) mediante un agente que actúe en tu nombre. La mejor forma de encontrar direcciones de agentes "y editoriales" es en algún anuario profesional del mundo editorial. (Asegúrate bien de dirigirte a las personas adecuadas; por ejemplo, no envíes una novela de ciencia ficción a una editorial de temas médicos). Espera. Reza. Así conseguí publicar Harry Potter.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[En los últimos años me he carteado con unas cuantas personas (aunque en ocasiones, cuando estoy trabajando de lleno en un libro, no soy muy cumplidora) pero, a decir verdad, creo que no tengo sitio para más gente. Jessica y David necesitan de mí: el resto de vosotros tenéis millones de amigos para escribir, ¡pero mis hijos no pueden elegir otra madre y ahora son ellos quienes más necesitan de mi tiempo!]]></c></r>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Desde siempre... Quise ser escritora desde el momento en que supe qué era un escritor. Tengo el temperamento perfecto para ser escritora: me siento del todo feliz sola en una habitación, inventando cosas.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Sí, he escrito bastante, pero nada publicado (no os perdéis nada, os lo aseguro). Lo primero que escribí fueron las historias de un conejo llamado simplemente Rabbit. Las escribí cuando tenía entre seis y ocho años. Y a los once escribí una novela sobre siete diamantes con una maldición y las personas por cuyas manos pasaban. Desde entonces he escrito montones de cosas: historias cortas, fragmentos de novelas para adultos, de todo.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[Durante un tiempo fui "ayudante de investigación" de Amnistía Internacional; fue una experiencia muy interesante, aunque no creo haber sido de mucha ayuda, ya que soy una desorganizada terminal (mi escritorio es un ejemplo muy gráfico). Los otros trabajos que he tenido durante un periodo prolongado, aparte de escribir, fueron en la enseñanza: fui profesora de francés en Escocia y de inglés en Portugal.]]></c></r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[Mi pertenencia material favorita es nuestra casa en el norte de Escocia, un lugar muy tranquilo en el que nos lo pasamos en grande con la familia y los amigos. Pero, seguramente, lo mejor que me han proporcionado mis ingresos es la falta de preocupaciones. No he olvidado lo que es no saber si te alcanzará el dinero para pagar las facturas. No tener que volver a pensar en esas cosas es el mayor lujo del mundo.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[Me encantan Harry, Hermione, Ron, Hagrid, Dumbledore, Ginny, Fred, George y Lupin. Me gusta escribir el personaje de Snape (aunque no me gustaría conocerlo). Mi personaje favorito de los nuevos es Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[Espero que de Gryffindor. Lo que más valoro de todo es el valor.]]></c></r></rs></x>
<?php } elseif($lang == "de" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[10]]></c><c n="a"><![CDATA[Jessica liebt die Bücher, was nett von ihr ist, weil sie mich schon seit so langer Zeit mit Harry teilen muss. David hat keinen blassen Schimmer, wer Harry Potter ist – deshalb genieße ich seine Gesellschaft ganz besonders!]]></c></r>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[Ich würde dasselbe sehen wie Molly Weasley, als sie im „Orden des Phönix“ einen Irrwicht aus dem verschlossenen Schrank ließ - meine Angehörigen, tot. Wenn es aber um Ängste geht, die nur mich persönlich betreffen, wäre es wohl die Furcht, lebendig begraben zu werden. Wer weiß, wie ein Irrwicht das darstellen würde - vielleicht als Sarg, der sich um mich schließt? Wurcks.]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[Ich habe noch Verschiedenes in der Schublade, auf das ich vielleicht noch zurückkomme. Oder ich schreibe etwas völlig anderes. Ich weiß es wirklich noch nicht.]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[Wie meine peniblen Fans bezeugen können, passieren mir durchaus Ausrutscher! Mehrere Klassenräume wechseln von Buch zu Buch auf mysteriöse Weise das Stockwerk - und das sind noch die harmlosesten Kontinuitätsfehler! Die meisten Fansites zeigen auf, wo ich Fehler gemacht habe. Aber an den wichtigen Dingen ändert sich nichts von Buch zu Buch, weil ich die Geschichte schon vor langer Zeit geplant habe und sie daher klar vor meinem geistigen Auge steht.
]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Das schwankt zwischen zehn Minuten (mit einem so kleinen Baby schaffe ich im Moment nicht mehr!) und zehn Stunden. Ich schreibe gern die ganze Nacht hindurch, aber auch das ist zur Zeit nicht machbar - ich muss zusehen, dass ich Schlaf bekomme, wann immer ich kann!]]></c></r>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[Das volle Grauen meines peinlichsten Augenblicks kann ich auf gar keinen Fall enthüllen; es war 1984, in einer Kneipe in Exeter (in dieser Stadt an der Südküste Englands habe ich die Universität besucht), und ich habe einen Witz gemacht, der auf spektakuläre Weise nach hinten losging. Meine Freundin Pauline, die auch andernorts auf dieser Site erwähnt wird, war dabei (ich muss besonders nett zu ihr sein, damit sie die KLAPPE HÄLT).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[Ich bin ja echt gerührt, dass jemand das gern tun würde, aber bei mir gäbe es da wirklich nicht viel zu tun! Ich sitze einfach in einem Zimmer oder einem Café herum und schreibe, und das bringe ich genauso gut ohne jede Hilfe fertig!]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[Innerhalb von Europa bin ich ziemlich viel herumgereist, und in den USA war ich auch ein paar Mal, allerdings meist auf Buchtour; ich habe also eine Menge Hotelzimmer, Buchhandlungen und Fernsehstudios zu sehen bekommen, und dazwischen ab und zu einen kurzen Blick auf berühmte Sehenswürdigkeiten geworfen. New York ist die Ausnahme; dort war ich sozusagen als normaler Mensch, und es hat mir sehr gut gefallen. Letztes Jahr war ich erstmals in Afrika auf Safari; David war erst fünf Monate alt, daher war das gar nicht so einfach, aber wirklich wunderschön.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[Ich fürchte, die Antwort darauf ist „Nein“, wenn auch Amerikaner und andere Staatsangehörige am Rande der Quidditch-Weltmeisterschaft aufgetaucht sind. Der Grund ist offensichtlich: Ich schreibe über Großbritannien und eine britische Schule; daher gibt es keinen logischen Grund, dort „nur so“ Ausländer einzuführen, denn die würden sicherlich fehl am Platze wirken. Ich erhalte häufig Vorschläge, was ich in die Harry Potter-Bücher noch alles hineinnehmen sollte, aber diese Geschichten gehören mir, und mir allein; wenn jemand gern über amerikanische Zauberer schreiben möchte, hindert ihn natürlich niemand daran, sein eigenes Buch zu verfassen!]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[Schaut immer wieder hier nach!]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[Zuerst muss man natürlich etwas schreiben, das ein Verlag herausgeben möchte (einer reicht ja, aber es kann eine Weile dauern, ihn zu finden. Wenn man von jedem einzelnen existierenden Verlag abgelehnt wird, muss man sich wohl schließlich eingestehen, dass das, was man geschrieben hat, nicht zur Veröffentlichung taugt). Als Nächstes muss man sich an den Verlag wenden, entweder direkt oder (was empfehlenswert ist, wenn irgend machbar) indem man sich einen Agenten sucht, der einen hierbei vertritt. Die Kontaktadressen von Agenten und Verlegern entnimmt man am besten dem „Deutschen Jahrbuch für Autoren & Autorinnen“, das jedes Jahr in einer aktualisierten Ausgabe erscheint. (Man sollte genau darauf achten, dass man sich an die richtigen Leute wendet und nicht etwa ein Science-Fiction-Manuskript an einen Verlag für medizinische Lehrbücher schickt.) Dann heißt es warten. Und beten. Auf diese Weise wurde Harry Potter veröffentlicht.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[In den letzten Jahren habe ich mir zwar ein paar Brieffreunde zugelegt (obwohl ich manchmal ein wenig unzuverlässig bin, wenn ich hart an einem Buch arbeite!), aber, um ganz ehrlich zu sein: Für noch mehr Brieffreunde reicht es einfach nicht. Jessica und David haben nun mal Vorrang: Alle anderen können sich schließlich unter Millionen Menschen einen Brieffreund suchen, aber diese beiden haben keine andere Mutter zur Auswahl, und daher ist es ihr gutes Recht, einen Großteil meiner Zeit für sich zu beanspruchen!]]></c></r>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Schon immer... sobald ich wusste, was ein Schriftsteller ist, wollte ich einer sein. Ich habe das perfekte Temperament für einen Schriftsteller; ich sitze gern allein im Zimmer herum und denke mir Sachen aus.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Ja, jede Menge sogar, aber nichts davon wurde veröffentlicht (und glaubt mir, ihr habt da nichts verpasst). Das erste, was ich je geschrieben habe, waren die Kaninchen-Geschichten, über ein Kaninchen namens Kaninchen. Da war ich so zwischen sechs und acht Jahren alt. Dann, mit elf, schrieb ich einen Roman über sieben mit einem Fluch belegte Diamanten und die Leute, denen sie gehörten. Seither habe ich ziemlich viel geschrieben: Kurzgeschichten, Teile von Romanen für Erwachsene, so alles Mögliche.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[Eine Zeitlang war ich „Forschungsassistentin“ bei Amnesty International; das war zwar sehr interessant, aber ich glaube nicht, dass die viel von mir hatten, denn leider bin ich hoffnungslos chaotisch (mein Schreibtisch ist dafür ein einschlägiges Beispiel). Ansonsten waren meine längsten Jobs außer der Schriftstellerei Lehrerstellen; ich habe in Schottland Französisch unterrichtet, und Englisch in Portugal.]]></c></r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[Von den materiellen Dingen ist mir unser Haus im Norden Schottlands am liebsten. Es ist sehr friedlich dort, und wir haben eine Menge Spaß mit Freunden und Familie. Das Beste, was ich durch meine Einkünfte habe, ist aber, dass ich mir keine Sorgen mehr machen muss. Ich habe nicht vergessen, wie man sich fühlt, wenn man nicht weiß, ob das Geld reicht, um die Rechnungen zu bezahlen. Dass ich darüber nicht mehr nachzudenken brauche, ist der größte Luxus der Welt.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[Ich mag besonders: Harry, Hermine, Ron, Hagrid, Dumbledore, Ginny, Fred, George und Lupin. Es macht mir Spaß, über Snape zu schreiben (aber begegnen möchte ich ihm nicht unbedingt). Unter den neuen Charakteren mag ich am liebsten Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[Gryffindor, hoffe ich doch. Mut ist mir wichtiger als fast alles andere.]]></c></r></rs></x>
<?php } elseif($lang == "it" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[10]]></c><c n="a"><![CDATA[A Jessica piacciono molto i libri, il che è molto carino da parte sua visto che ha dovuto dividermi a lungo con Harry. David non ha idea di chi sia Harry Potter, e questo lo rende una compagnia molto riposante!]]></c></r>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[Nella stessa cosa che vide Molly Weasley quando fece uscire un Molliccio dall’armadietto chiuso a chiave in “Ordine della Fenice”: i miei cari, morti. Se invece state parlando di una paura che riguarda solo me, è quella di essere sepolta viva. Non so esattamente come farebbe un Molliccio a rappresentare questa paura; forse si trasformerebbe in una bara che mi si chiude attorno? Argh.]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[Ci sono cose che languono in vari cassetti e potrei tornarvi, ma potrei anche scrivere qualcosa di completamente diverso. Non lo so proprio.]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[Come ti diranno i fan con manie ossessive, commetto vari errorini! Diverse aule cambiano misteriosamente piano da un libro all’altro, e questi sono gli errori meno gravi. La maggior parte dei siti di fan ti indicheranno i miei errori. Ma per le cose più importanti non ci sono incoerenze tra un libro e l’altro, perché la trama è stata creata tanto tempo fa e l’ho ben chiara in mente.
]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Da dieci minuti (che è tutto quello che posso permettermi al momento, con una bimba così piccola!) a dieci ore. Mi piace scrivere per tutta la notte, ma neanche quello è fattibile al momento: ho bisogno di dormire, quando posso!]]></c></r>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[Non posso proprio rivelare gli orripilanti dettagli del mio momento più imbarazzante, ma ha avuto luogo nel 1984 in un pub di Exeter (una città sulla costa meridionale dell'Inghilterra, dove ho frequentato l'università); feci uno scherzo che mi si ritorse contro in maniera spettacolare. Fu presente all'intero orrore la mia amica Pauline, che ho nominato in un'altra parte di questo sito (devo tenerla buona, per paura che PARLI).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[Mi commuove proprio sapere che ci sono persone che lo desiderano, ma la verità è che non c'è molto da fare! Non faccio altro che stare seduta in una stanza o in un caffè e scrivere, e questo posso decisamente farlo senza assistenza!]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[Ho girato abbastanza l'Europa e sono stata diverse volte negli Stati Uniti (anche se nella maggior parte dei casi era per la promozione dei libri, il che significa che ho visto una montagna di camere d'albergo, di librerie e di studi televisivi e, fra l'uno e l'altro, ho potuto intravedere brevemente qualche luogo famoso). L'eccezione è New York, che ho visitato da normale essere umano e che amo. L'anno scorso, per la prima volta, ho partecipato a un safari in Africa; non è stata un'impresa facile perché David aveva solo cinque mesi, ma è stato davvero meraviglioso.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[Temo che la risposta sia "no", anche se si sono intravisti americani e persone di altre nazionalità alla Coppa del Mondo di Quidditch. Il motivo è evidente: sto scrivendo sulla Gran Bretagna e su una scuola britannica e non c'è una ragione logica di inserire personaggi stranieri, che, ne sono sicura, sembrerebbero immotivati. Ricevo spesso suggerimenti su che cosa dovrei inserire nei libri di Harry Potter, ma queste storie sono mie e solo mie; se qualcuno vuole scrivere sui maghi americani, naturalmente è liberissimo di scrivere il suo libro!]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[Tenete d'occhio questo sito!]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[Innanzitutto devi scrivere qualcosa che a un editore interessi pubblicare (ne basta uno, ma a volte ci vuole un po' a trovarlo. Se ciò che hai scritto viene rifiutato da ogni singola casa editrice esistente, beh, dovrai prendere in considerazione la possibilità che non sia pubblicabile). Poi devi contattare una casa editrice, o direttamente o (il che è consigliabile, se ci riesci) attraverso un agente che agirà a nome tuo. Il modo migliore per trovare gli indirizzi delle case editrici e degli agenti letterari è consultare "The Writer's and Artist's Yearbook", che viene aggiornato ogni anno. Accertati di scrivere alle persone giuste; per esempio, non mandare fantascienza a un editore di testi medici! Aspetta. Prega. È così che Harry Potter è stato pubblicato.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[Ho iniziato qualche corrispondenza negli ultimi anni (anche se talvolta sono un po' inaffidabile, quando sono occupatissima con un libro!) ma, in tutta sincerità, non credo proprio di avere tempo per altri amici-di-penna. Jessica e David devono essere al primo posto: voi fan avete milioni di corrispondenti fra cui scegliere ma loro non possono scegliere una madre alternativa, e quindi hanno molto più bisogno del mio tempo!]]></c></r>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Lo desidero da sempre… appena ho capito che cosa sono gli scrittori, ho voluto diventarlo. Ho il temperamento perfetto per una scrittrice; se posso stare da sola in una stanza a inventare cose, sono felice.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Sì, tante cose, anche se nessuna è stata pubblicata (non è una grave perdita, ve lo assicuro). Le prime cose che ho scritto erano le storie di Coniglio, che parlavano di un coniglio di nome Coniglio; le ho scritte tra i sei e gli otto anni. Poi, quando ne avevo undici, ho scritto un romanzo su sette diamanti maledetti e sui loro proprietari. Da allora ho scritto tanta roba: racconti, parti di romanzi per adulti, cose di ogni tipo.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[Per un po’ sono stata “assistente ricercatrice” ad Amnesty International; era molto interessante ma non credo di essere stata di grande utilità, perché sono atrocemente disorganizzata (per una dimostrazione grafica, vedi la mia scrivania). Il lavoro che ho svolto più a lungo, escludendo lo scrivere, è stato l’insegnamento: ho insegnato francese in Scozia e inglese in Portogallo.]]></c></r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[La mia cosa materiale preferita è la nostra casa nel nord della Scozia, un posto pieno di pace dove ci divertiamo molto con amici e parenti. Probabilmente la cosa migliore in assoluto che mi hanno permesso i miei guadagni, però, è l’assenza di preoccupazioni economiche. Non ho dimenticato come ci si sente quando non si sa se i soldi basteranno per pagare le bollette... Non doverci più pensare è il lusso più grande del mondo.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[Amo: Harry, Hermione, Ron, Hagrid, Silente, Ginny, Fred, George e Lupin. Amo descrivere (anche se non necessariamente vorrei incontrare) Piton. Il personaggio nuovo che preferisco è Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[In Grifondoro, spero. Per me il coraggio è più importante di quasi ogni altra cosa.]]></c></r></rs></x>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[The same thing Molly Weasley saw when she let a Boggart out of the locked cabinet in 'Order of the Phoenix' – my loved ones, dead.  If, however, you are talking about a fear that concerns only me, it would be being buried alive.  I'm not sure how a Boggart would represent that; perhaps turn into a coffin around me?  Urgh.]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[There are things languishing in various drawers that I might return to, but I might write something completely different.  I really don't know.]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[As obsessive fans will tell you, I do slip up!  Several classrooms move floors mysteriously between books and these are the least serious continuity errors!  Most of the fansites will point you in the direction of my mistakes.  But the essentials remain consistent from book to book because the story has been plotted for a long time and it is clear in my mind.
]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Anything from ten minutes (which is all I can get at the moment with such a young baby!) to ten hours.  I love writing through the night, but again, that's not feasible just now – I need to sleep when I can!]]></c></r>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[I cannot possibly reveal the full horror of my most embarrassing moment, but it took place in a pub in Exeter (which is a town in the south coast of England, where I went to university) in 1984 and involved a joke made by me that backfired spectacularly.  The whole debacle was witnessed by my friend Pauline, who is mentioned elsewhere on this fansite (I have to keep her happy in case she TELLS).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[I am really touched that anyone would like to do this, but the truth is that there's nothing much to do!  I just sit in a room or a cafe and write and I'm more than capable of doing that without assistance!]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[I've travelled quite a bit within Europe and I've been to the States several times, mostly on book tours though, which means I see a lot of hotel rooms, book stores and television studios with brief glimpses of famous landmarks in between.  The exception is New York, which I've visited as a normal human, and which I love.  I went on safari in Africa for the first time last year, which was a challenge as David was only five months old at the time, but which was really wonderful.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[I'm afraid the answer to this is 'no', although you have glimpsed Americans and other nationalities at the Quidditch World Cup.  The reason is obvious: I am writing about Britain and a British school and there is no logical reason to insert foreigners for the sake of it, because I'm sure they would feel gratuitous.  I often get suggestions about what I ought to insert into Harry Potter books, but these are my stories and mine alone; if anyone wants to write about American wizards they are of course free to write their own book!]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[Watch this space!]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[Firstly, you need to write something that a publisher would want to publish (it only takes one, but it might take a while to find them.  If you are turned down by every single publisher in existence, you will have to consider the possibility that what you have written is not publishable).  Next, you need to approach the publisher, either directly, or (which is advisable if you can manage it) by securing an agent who will act on your behalf.  The best way to find agents' and publishers' addresses is to consult 'The Writer's and Artist's Yearbook', which is updated every year.  (Double-check that you are writing to the right person/people; don't, for example, send science fiction to a publisher of medical textbooks.)  Wait.  Pray.  This is the way Harry Potter got published.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[I have picked up a few penpals over the last few years (though I'm sometimes a bit unreliable when I'm working hard on a book!) but to be very honest, I don't think I have room for any more.  Jessica and David have to come first: the rest of you have millions of penpals to choose from, but they can't choose an alternative mother, so they really do need my time most!]]></c></r>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Always... as soon as I knew what writers were, I wanted to be one.  I've got the perfect temperament for a writer; perfectly happy alone in a room, making things up.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Yes, quite a lot, though none of it is published (which is no loss, I assure you).  The first things I wrote were the Rabbit stories, which were about a rabbit called Rabbit.  I wrote them between the ages of six and eight.  Then when I was eleven I wrote a novel about seven cursed diamonds and the people who owned them.  Since then I’ve written loads: short stories, bits of novels for adults, all kinds of things.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[I was a 'research assistant' at Amnesty International for a while, which was very interesting but I don't think I was much of an asset as I am terminally disorganised (see my desk top for a graphic demonstration).  The longest jobs I have had other than writing have been teaching; I taught French in Scotland and English in Portugal.]]></c></r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[My favourite material thing is our house in the north of Scotland, where it is very peaceful and we have a lot of fun with family and friends.  Probably the very best thing my earnings have given me, though, is absence of worry.  I have not forgotten what it feels like to worry whether you'll have enough money to pay the bills.  Not to have to think about that any more is the biggest luxury in the world.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[I love: Harry, Hermione, Ron, Hagrid, Dumbledore, Ginny, Fred, George and Lupin.  I love writing (though would not necessarily want to meet) Snape.  My favourite new character is Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[Gryffindor, I hope.  I value courage beyond almost anything.]]></c></r></rs></x>
<?php } else {?>
<x><rs n="faq" c="ID,q,sp,a">
	<?php if($website_version > 0 ){?>
<r><c n="ID"><![CDATA[10]]></c><c n="a"><![CDATA[Jessica loves the books, which is very nice of her as she's had to share me with Harry for so long.  David has no idea who Harry Potter is, which makes him very restful company!]]></c></r>
	<?php } if($website_version > 1 ){?>
<r><c n="ID"><![CDATA[106]]></c><c n="a"><![CDATA[The same thing Molly Weasley saw when she let a Boggart out of the locked cabinet in 'Order of the Phoenix' – my loved ones, dead.  If, however, you are talking about a fear that concerns only me, it would be being buried alive.  I'm not sure how a Boggart would represent that; perhaps turn into a coffin around me?  Urgh.]]></c></r>
<r><c n="ID"><![CDATA[107]]></c><c n="a"><![CDATA[There are things languishing in various drawers that I might return to, but I might write something completely different.  I really don't know.]]></c></r>
<r><c n="ID"><![CDATA[108]]></c><c n="a"><![CDATA[As obsessive fans will tell you, I do slip up!  Several classrooms move floors mysteriously between books and these are the least serious continuity errors!  Most of the fansites will point you in the direction of my mistakes.  But the essentials remain consistent from book to book because the story has been plotted for a long time and it is clear in my mind.]]></c></r>
<r><c n="ID"><![CDATA[109]]></c><c n="a"><![CDATA[Anything from ten minutes (which is all I can get at the moment with such a young baby!) to ten hours.  I love writing through the night, but again, that's not feasible just now – I need to sleep when I can!]]></c></r>
	<?php } if($website_version > 5 ){?>
<r><c n="ID"><![CDATA[131]]></c><c n="a"><![CDATA[I’ve just finished the fourth Galbraith novel, Lethal White, and I’m now writing the screenplay for Fantastic Beasts 3. After that I’ll be writing another book for children. I’ve been playing with the (non-Harry Potter/wizarding world) story for about six years, so it’s about time I get it down on paper.]]></c></r>
<r><c n="ID"><![CDATA[132]]></c><c n="a"><![CDATA[I try to start work before 9am. My writing room is probably my favourite place in the world. It’s in the garden, about a minute’s walk from the house. There’s a central room where I work, a kettle, a sink and a cupboard-sized bathroom. The radio is usually tuned to classical music, because I find human voices the most distracting when I’m working, although a background buzz, as in a café, is always comforting. I used to love writing in cafés and gave it up reluctantly, but part of the point of being alone in a crowd was being happily anonymous and free to people-watch, and when you’re the one being watched, you become too self-conscious to work.

The earlier in the day I start, the more productive I am. In the last year or two I’ve put in a couple of all-nighters on the screenplays for Fantastic Beasts, but otherwise I try and keep my writing to the daytime. If I’ve started around nine, I can usually work through to about 3pm before I need more than a short break. During this writing time, I generally manage to drink eight or nine mugs of tea. Being incredibly clumsy, prefer eating things that won’t ruin the keyboard when dropped. Popcorn’s ideal.]]></c></r>
<r><c n="ID"><![CDATA[133]]></c><c n="a"><![CDATA[By nature I’m quite solitary, so novels and I suit each other perfectly, but the collaborations I’ve been involved in have been pure joy, mainly because of the people involved.

For ten years I said no to proposals to adapt Harry for the stage, usually as a musical, and using the existing books. So when I met producers Sonia Friedman and Colin Callender, I wasn’t sure what I was going to hear. I only knew that they wanted to do something new, which was intriguing, because I had no desire to go endlessly back over old ground.

I couldn’t have asked for better collaborators on the stage play than John Tiffany (director) and Jack Thorne (writer). Incredibly, John and I knew each to say hello to years ago, when I used to write in the café at the Traverse Theatre in Edinburgh. When we met for the first time about Cursed Child, I stared at him, thinking, he looks so familiar, where have I met him? And he told me, and the whole thing felt oddly fated.

I told John and Jack what I thought had happened to Harry, Ron and Hermione in later years, explained how focused I was on Harry’s son Albus, who’d been given the burden of not one, but three legendary names, and together we created the story that Jack wrote.

I have so many wonderful memories of the earliest rehearsals, of seeing the costumes and illusions for the first time, but what I remember most fondly about the three of us working together is the laughter. I loved the process from beginning to end.

I particularly remember the first full dress rehearsal I watched. By this time I knew the script backwards, had heard it read all the way through and watched individual scenes acted, but nothing prepared me for seeing it in its entirety, in the theatre. I found it incredibly moving and it brought back a tsunami of memories about the seventeen years I spent creating the characters and writing the Harry Potter books. John and Jack did a superb job. Very few people have come inside the world with me and it creates a particular bond.

The big difference between theatre and movies for me is scale. When I go down to WB Studios Leavesden and see a thousand people at work on Fantastic Beasts, building sets, making costumes, doing digital effects, making models and props and all the hundreds of other things that go into making a movie, it can feel utterly overwhelming. Terrifying thoughts run through your mind, such as, I must not break an arm, because all these people’s jobs depend on me getting the screenplay finished.

However, at the heart of the process is a very similar collaboration to the one I had on Cursed Child, this time with David Yates, the director, and Steve Kloves, who was the writer on seven of the eight Potter films and is a producer on Beasts.

In spite of the fact that I’d watched Steve close up for all those years, I found screenwriting utterly different from novel writing and very challenging at first. Basically, I learned how to write a screenplay as I went along, knowing that the movie was definitely going to be made, which is, to say the least, atypical. Steve gives great, pithy notes. The one that made me laugh longest was when I had a character in a cut scene in an early draft say, ‘They’re children!’. He said, ‘Yeah, unless we’ve got the casting badly wrong, that’ll probably be obvious.’

David knows the world of Potter intimately now, after directing four of the eight original movies. I love working with him. I learn a lot just listening to him talk about images. Even though I have a highly visual imagination, I’ve had to learn just how much can be said onscreen without a word, and David and Steve have taught me that.

The thing with movies is, however frustrated you get with the screenwriting process, and right at the moment when you think ‘never again, this is too hard’, you go down to the film set and join in with one big glorious game of pretend, with the world’s best pretenders saying your words, and dressing out of the most fabulous dressing up box, and what with the lights and the smoke and the music you’re suddenly in love with the process all over again.]]></c></r>
<r><c n="ID"><![CDATA[134]]></c><c n="a"><![CDATA[Warner Bros and David Yates, the director, have always let me have my say, though not necessarily the final word. That’s true of all the producers, of whom I’m only one: our input is taken seriously but it is very much a collaborative effort.  The director is ultimately responsible for everything that’s seen on the screen. As the screenwriter, the majority of my input comes at an earlier stage.]]></c></r>
<r><c n="ID"><![CDATA[135]]></c><c n="a"><![CDATA[This is a tricky question in some ways, because a writer who truly only wrote for themselves probably wouldn’t try and get published. At the same time, I agree with Cyril Connolly’s words: ‘Better to write for yourself and have no public, than write for the public and have no self.’

I certainly write ‘for myself’ in the sense that I have to write. It’s almost a compulsion. I need to do it. I don’t feel like myself if I’m not writing regularly, and I feel restless and odd if I have nothing to write, which these days is never, because I’ve got so many different projects on the go, by choice. I also write for myself in that I need to feel excited about a story to want to capture it on paper. I’m afraid I couldn’t write anything just because I knew people wanted it. The impetus always has to come from within.

On the other hand, no story lives unless someone is prepared to listen. As a writer, your highest aspiration is to touch people, to connect, to amuse or console. What could be more wonderful than hearing that your book helped somebody through a tough time? I think of the times when books have been my best consolation and source of strength, and I’m proud beyond words when I hear that anything I wrote did the same for other people.]]></c></r>
	<?php }?>
<r><c n="ID"><![CDATA[41]]></c><c n="a"><![CDATA[I cannot possibly reveal the full horror of my most embarrassing moment, but it took place in a pub in Exeter (which is a town in the south coast of England, where I went to university) in 1984 and involved a joke made by me that backfired spectacularly.  The whole debacle was witnessed by my friend Pauline, who is mentioned elsewhere on this fansite (I have to keep her happy in case she TELLS).]]></c></r>
<r><c n="ID"><![CDATA[42]]></c><c n="a"><![CDATA[I am really touched that anyone would like to do this, but the truth is that there's nothing much to do!  I just sit in a room or a cafe and write and I'm more than capable of doing that without assistance!]]></c></r>
<r><c n="ID"><![CDATA[43]]></c><c n="a"><![CDATA[I've travelled quite a bit within Europe and I've been to the States several times, mostly on book tours though, which means I see a lot of hotel rooms, book stores and television studios with brief glimpses of famous landmarks in between.  The exception is New York, which I've visited as a normal human, and which I love.  I went on safari in Africa for the first time last year, which was a challenge as David was only five months old at the time, but which was really wonderful.]]></c></r>
<r><c n="ID"><![CDATA[44]]></c><c n="a"><![CDATA[I'm afraid the answer to this is 'no', although you have glimpsed Americans and other nationalities at the Quidditch World Cup.  The reason is obvious: I am writing about Britain and a British school and there is no logical reason to insert foreigners for the sake of it, because I'm sure they would feel gratuitous.  I often get suggestions about what I ought to insert into Harry Potter books, but these are my stories and mine alone; if anyone wants to write about American wizards they are of course free to write their own book!]]></c></r>
<r><c n="ID"><![CDATA[45]]></c><c n="a"><![CDATA[Watch this space!]]></c></r>
<r><c n="ID"><![CDATA[46]]></c><c n="a"><![CDATA[Firstly, you need to write something that a publisher would want to publish (it only takes one, but it might take a while to find them.  If you are turned down by every single publisher in existence, you will have to consider the possibility that what you have written is not publishable).  Next, you need to approach the publisher, either directly, or (which is advisable if you can manage it) by securing an agent who will act on your behalf.  The best way to find agents' and publishers' addresses is to consult 'The Writer's and Artist's Yearbook', which is updated every year.  (Double-check that you are writing to the right person/people; don't, for example, send science fiction to a publisher of medical textbooks.)  Wait.  Pray.  This is the way Harry Potter got published.]]></c></r>
<r><c n="ID"><![CDATA[47]]></c><c n="a"><![CDATA[I have picked up a few penpals over the last few years (though I'm sometimes a bit unreliable when I'm working hard on a book!) but to be very honest, I don't think I have room for any more.  Jessica and David have to come first: the rest of you have millions of penpals to choose from, but they can't choose an alternative mother, so they really do need my time most!]]></c></r>
	<?php if($website_version > 0 ){?>
<r><c n="ID"><![CDATA[5]]></c><c n="a"><![CDATA[Always... as soon as I knew what writers were, I wanted to be one.  I've got the perfect temperament for a writer; perfectly happy alone in a room, making things up.]]></c></r>
<r><c n="ID"><![CDATA[51]]></c><c n="a"><![CDATA[Yes, quite a lot, though none of it is published (which is no loss, I assure you).  The first things I wrote were the Rabbit stories, which were about a rabbit called Rabbit.  I wrote them between the ages of six and eight.  Then when I was eleven I wrote a novel about seven cursed diamonds and the people who owned them.  Since then I’ve written loads: short stories, bits of novels for adults, all kinds of things.]]></c></r>
<r><c n="ID"><![CDATA[7]]></c><c n="a"><![CDATA[I was a 'research assistant' at Amnesty International for a while, which was very interesting but I don't think I was much of an asset as I am terminally disorganised (see my desk top for a graphic demonstration).  The longest jobs I have had other than writing have been teaching; I taught French in Scotland and English in Portugal.]]></c>///</r>
<r><c n="ID"><![CDATA[75]]></c><c n="a"><![CDATA[My favourite material thing is our house in the north of Scotland, where it is very peaceful and we have a lot of fun with family and friends.  Probably the very best thing my earnings have given me, though, is absence of worry.  I have not forgotten what it feels like to worry whether you'll have enough money to pay the bills.  Not to have to think about that any more is the biggest luxury in the world.]]></c></r>
<r><c n="ID"><![CDATA[8]]></c><c n="a"><![CDATA[I love: Harry, Hermione, Ron, Hagrid, Dumbledore, Ginny, Fred, George and Lupin.  I love writing (though would not necessarily want to meet) Snape.  My favourite new character is Luna Lovegood.]]></c></r>
<r><c n="ID"><![CDATA[9]]></c><c n="a"><![CDATA[Gryffindor, I hope.  I value courage beyond almost anything.]]></c></r>
	<?php }?>
</rs></x>
<?php } ?>