<?php $lang = (isset($_GET['lang']))? $_GET['lang'] : ""; 
$website_version = (file_exists("../config.ini"))?(parse_ini_file("../config.ini")["website_version"]):"4"; ?>

<?php if($lang == "fr" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[1]]></c><c n="a"><![CDATA[Chacun de mes soixante et quelque éditeurs, mon agent, mes amis, les membres de ma famille et mes voisins sont constamment contactés par des gens souhaitant une dédicace. Il me serait hélas matériellement impossible de dédicacer tous ces livres même si j'arrêtais d'écrire, de manger et de dormir. En ce moment, je n'accorde de dédicaces que lors de manifestations caritatives ou d'occasions très spéciales. C'est une situation que je regrette vraiment, mais je pense que vous préférez me savoir en train d'écrire les tomes six et sept plutôt que de dédicacer les cinq premiers romans. Alors, s'il vous plaît, de grâce, ne m'envoyez pas vos exemplaires des romans afin que je les dédicace. Je ne vois même plus les livres qui me sont envoyés : ils sont systématiquement retournés à l'expéditeur.]]></c></r>
<r><c n="ID"><![CDATA[2]]></c><c n="a"><![CDATA[Mes éditeurs me feront parvenir vos lettres.]]></c></r>
<r><c n="ID"><![CDATA[3]]></c><c n="a"><![CDATA[Je crains fort de n'avoir aucun contrôle sur la distribution des rôles. Mieux vaut vous adresser directement à Warner Bros.]]></c></r>
<r><c n="ID"><![CDATA[4]]></c><c n="a"><![CDATA[Les romans sont planifiés depuis si longtemps qu'il ne reste plus la moindre place pour de nouvelles idées ! Mais les fictions écrites par les fans sont vraiment amusantes et je suis très fière que Harry Potter ait inspiré tant de créativité !]]></c></r>
<r><c n="ID"><![CDATA[78]]></c><c n="a"><![CDATA[PARLEZ-EN À QUELQU'UN, que ce soit votre mère, votre père, une tante, un oncle, un professeur, un frère, une sœur, un adulte de confiance... Peu importe qui, mais dites-le à quelqu'un. Si la première personne à laquelle vous en parlez ne semble pas comprendre la gravité du problème, adressez-vous à quelqu'un d'autre. Je sais qu'il est très dur de reconnaître et d'avouer que l'on est brutalisé ou racketté, mais c'est vraiment crucial si vous voulez y mettre fin. La vie à l'école peut être très dure et les adultes qui l'ont oublié sont des idiots. N'ayez pas honte : parlez-en.]]></c></r>
<r><c n="ID"><![CDATA[79]]></c><c n="a"><![CDATA[Je n'en sais rien. C'est à la Warner Brothers que vous devriez poser cette question ! Vous trouverez l'adresse du site dans ma rubrique « Liens ». Je crains de n'avoir aucune autorité sur ce genre de question.]]></c></r>
<r><c n="ID"><![CDATA[80]]></c><c n="a"><![CDATA[J'ignore ce que vous entendez au juste par « intermédiaires ». La plupart des écrivains recourent à des agents dont le travail consiste à négocier pour eux les contrats (les écrivains ne sont pas nécessairement d'excellents hommes ou femmes d'affaires) et, bien qu'il ne soit pas indispensable d'avoir un agent, je conseillerais à toute débutant de tâcher d'en trouver un. En dehors de votre agent, vous êtes en contact avec un rédacteur ou correcteur et, éventuellement, avec les gens chargés du marketing de votre livre. Aucune de ces personnes ne peut être qualifiée d'intermédiaire, elles font simplement partie du processus d'édition. Bien entendu, si vous souhaitez n'avoir affaire à personne, il vous reste la possibilité de l'édition à compte d'auteur, mais cela m'a toujours paru épouvantablement fastidieux.]]></c></r></rs></x>
<?php } elseif($lang == "es" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[1]]></c><c n="a"><![CDATA[Cada una de las sesentaytantas editoriales que publican mis libros, mi agente, mis amigos, mis familiares y mis vecinos son asaltados a diario por personas que quieren que les dedique su ejemplar. La triste verdad es que no podría firmar todos estos libros ni siquiera aunque dejase de escribir, comer y dormir. Últimamente sólo firmo libros para obras benéficas o en circunstancias muy especiales. Lo siento de verdad, pero creo que todos preferís que escriba los libros seis y siete a que pase el resto de mi vida firmando los libros uno al cinco. Por favor, por favor, por favor: no me enviéis libros para dedicar. Ya ni siquiera veo los libros que me envían, que son devueltos al instante al remitente.]]></c></r>
<r><c n="ID"><![CDATA[2]]></c><c n="a"><![CDATA[Mis editoriales me hacen llegar la correspondencia.]]></c></r>
<r><c n="ID"><![CDATA[3]]></c><c n="a"><![CDATA[No tengo ningún control sobre el casting. Deberíais escribir a Warner Bros.]]></c></r>
<r><c n="ID"><![CDATA[4]]></c><c n="a"><![CDATA[La planificación de los libros está hecha desde hace ya mucho tiempo, y apenas hay lugar para nuevas ideas. Sin embargo, reconozco que escribir novelas es muy divertido, ¡y me siento orgullosa de que Harry Potter haya inspirado tanta creatividad!]]></c></r>
<r><c n="ID"><![CDATA[78]]></c><c n="a"><![CDATA[DECÍRSELO A ALGUIEN, a tus padres, tíos, hermanos, a un profesor, a un amigo mayor, pero contárselo a alguien. Si la primera persona a la que se lo dices parece no comprender lo grave que es el problema, prueba con otra persona. Sé lo duro que es admitir que alguien te está maltratando, pero es esencial para acabar con tu sufrimiento. La vida en la escuela puede ser muy dura y cualquier adulto que lo haya olvidado es idiota. No sientas vergüenza: cuéntalo.]]></c></r>
<r><c n="ID"><![CDATA[79]]></c><c n="a"><![CDATA[No lo sé; ¡deberías ponerte en contacto con Warner Brothers! (Puedes acceder a su sitio web desde la sección "Enlaces"). Yo no tengo mucho poder en este tipo de cosas.]]></c></r>
<r><c n="ID"><![CDATA[80]]></c><c n="a"><![CDATA[No estoy muy segura de a qué te refieres por "intermediarios". La mayoría de los escritores tienen un agente cuyo trabajo consiste en negociar contratos en su nombre (los escritores no suelen ser buenos hombres o mujeres de negocios), y, aunque no es estrictamente necesario tener un agente, yo se lo recomendaría a cualquier autor novel. Aparte de tu agente, tendrás que tratar con un editor y tal vez con los responsables de la comercialización de tu libro. Ninguna de estas personas puede describirse como "intermediarios"; simplemente tienen su función dentro del proceso editorial. Por supuesto, si prefieres no implicar a nadie más, puedes hacer una edición propia, pero a mí esto siempre me ha parecido un montón de trabajo muy duro.]]></c></r></rs></x>
<?php } elseif($lang == "de" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[1]]></c><c n="a"><![CDATA[Jeder einzelne meiner über sechzig Verleger, mein Agent, meine Freunde, Verwandten und Nachbarn werden ständig von Leuten angesprochen, die ihre Bücher von mir signiert haben wollen. Traurig, aber wahr: Ich könnte alle diese Bücher selbst dann nicht signieren, wenn ich dafür das Schreiben, Essen und Schlafen aufgeben wollte. Heutzutage signiere ich Bücher nur noch für wohltätige Zwecke, oder unter ganz besonderen Umständen. Das tut mir aufrichtig Leid, aber ich denke, es ist euch allen lieber, wenn ich Buch sechs und sieben schreibe, als wenn ich für den Rest meines Lebens nur noch die Bücher eins bis fünf signiere. Also: bitte, bitte, bitte schickt mir keine Bücher mehr zum Unterschreiben. Die bekomme ich nämlich sowieso gar nicht erst zu sehen; sie gehen einfach zurück an den Absender.]]></c></r>
<r><c n="ID"><![CDATA[2]]></c><c n="a"><![CDATA[Meine Verleger leiten Briefe an mich weiter.]]></c></r>
<r><c n="ID"><![CDATA[3]]></c><c n="a"><![CDATA[Leider entzieht sich die Rollenbesetzung meiner Kontrolle. Am besten schreibst du an Warner Bros.]]></c></r>
<r><c n="ID"><![CDATA[4]]></c><c n="a"><![CDATA[Die Bücher sind schon seit so langer Zeit geplant, dass für weitere Ideen gar kein Platz mehr ist! Fan-Fiction macht mir aber wirklich Spaß, und ich bin ganz stolz darauf, dass Harry Potter so viel Kreativität inspiriert hat!]]></c></r>
<r><c n="ID"><![CDATA[78]]></c><c n="a"><![CDATA[SAG ES JEMANDEM – Mutter, Vater, Tante, Onkel, Lehrer, Bruder, Schwester, erwachsenen Freunden – ganz egal wem, aber sag es. Und wenn die erste Person, der du es sagst, nicht einsieht, wie groß das Problem ist, sag es jemand anderem. Ich weiß, es ist sehr schwer zuzugeben, dass man schikaniert wird, aber das ist absolut notwendig, wenn das Elend ein Ende haben soll. Das Leben in der Schule kann sehr hart sein, und wenn ein Erwachsener das vergessen hat, ist er ein Idiot. Also keine falsche Scham – erzähl es jemandem.]]></c></r>
<r><c n="ID"><![CDATA[79]]></c><c n="a"><![CDATA[Das weiß ich nicht, da müsst ihr euch bei Warner Brothers erkundigen! (Ihr findet deren Website bei mir im Abschnitt „Links“). Bedaure, aber auf solche Dinge habe ich keinen Einfluss.]]></c></r>
<r><c n="ID"><![CDATA[80]]></c><c n="a"><![CDATA[Ich weiß nicht genau, was hier mit „Mittelsmännern“ gemeint ist. Die meisten Schriftsteller haben Agenten, deren Aufgabe darin besteht, Verträge für sie auszuhandeln (Schriftsteller sind ja nicht unbedingt gute Geschäftsleute). Man muss zwar nicht unbedingt einen Agenten haben, aber ich würde jedem Neuling raten, sich einen zu nehmen, wenn es irgend möglich ist. Außer dem Agenten hat man noch mit einem Lektor zu tun, und vielleicht auch mit den Leuten, die das Buch vermarkten. Aber das sind alles keine „Mittelsmänner“, sie sind einfach am Vorgang der Veröffentlichung beteiligt. Wenn es dir natürlich lieber ist, dass sonst niemand damit zu tun hat, kannst du dein Buch auch im Selbstverlag herausgeben. Ich stelle mir allerdings vor, dass damit jede Menge harte Arbeit verbunden ist.]]></c></r></rs></x>
<?php } elseif($lang == "it" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[1]]></c><c n="a"><![CDATA[Tutti i miei sessanta e passa editori, il mio agente, gli amici, i parenti e i vicini sono continuamente contattati da persone che vogliono che firmi i loro libri. La triste verità è che non potrei firmare tutti quei libri neanche se rinunciassi a scrivere, a mangiare e a dormire. Al momento firmo libri solo per beneficenza o in circostanze molto particolari. Mi dispiace molto, ma credo che tutti voi preferiate che scriva il sesto e il settimo libro piuttosto che passare la vita a firmare i primi cinque. Quindi per favore, per favore, per favore: non inviatemi i vostri libri da firmare. Non vedo neanche i libri che mi vengono inviati; sono rispediti al mittente.]]></c></r>
<r><c n="ID"><![CDATA[2]]></c><c n="a"><![CDATA[I miei editori mi inoltrano le lettere.]]></c></r>
<r><c n="ID"><![CDATA[3]]></c><c n="a"><![CDATA[Non ho alcun controllo sul casting, temo. Il meglio che potete fare è scrivere alla Warner Bros.]]></c></r>
<r><c n="ID"><![CDATA[4]]></c><c n="a"><![CDATA[I libri sono stati progettati tanto tempo fa che non c'è più posto per nuove idee! Quello che inventano i fan è molto divertente, comunque, e sono molto fiera del fatto che Harry Potter abbia ispirato tanta creatività!]]></c></r>
<r><c n="ID"><![CDATA[78]]></c><c n="a"><![CDATA[DITELO A QUALCUNO. A chi volete: alla mamma, al papà, a una zia, uno zio, un insegnante, un fratello, una sorella, un amico adulto… ma parlatene. Se la prima persona a cui lo dite non sembra capire la gravità del problema, rivolgetevi a qualcun altro. Lo so, è molto difficile ammettere di essere vittime di prepotenze, ma è assolutamente essenziale per mettere fine al tormento. La vita scolastica può essere molto dura e qualsiasi adulto che l’abbia dimenticato è uno stupido, quindi non abbiate vergogna… ditelo.]]></c></r>
<r><c n="ID"><![CDATA[79]]></c><c n="a"><![CDATA[Non lo so; dovrete contattare la Warner Brothers! Potete accedere al loro sito dalla mia sezione “Collegamenti”. Io non ho alcun potere decisionale per cose del genere, temo.]]></c></r>
<r><c n="ID"><![CDATA[80]]></c><c n="a"><![CDATA[Non sono sicura di sapere che cosa intendete con “intermediari”. La maggior parte degli scrittori ha un agente, il cui compito consiste nel negoziare i contratti (visto che gli scrittori non sono necessariamente bravi negli affari); non è indispensabile avere un agente, ma consiglio a tutti gli scrittori principianti di procurarsene uno, se possono. Oltre all’agente c’è il revisore, e forse quelli del marketing. Nessuna di queste persone può essere definita “intermediario”; fanno semplicemente parte del processo di pubblicazione. Naturalmente si può sempre ricorrere all’autopubblicazione, se si vuole che nessun altro sia coinvolto, ma mi è sempre sembrata una faccenda complicata e faticosa.]]></c></r></rs></x>
<?php } else {?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[1]]></c><c n="a"><![CDATA[Every one of my sixty-something publishers, my agent, my friends, my relatives and my neighbours are constantly approached by people who want me to sign their books.  The sad truth is I couldn't sign all of these books even if I gave up writing, eating or sleeping.  These days the only books I sign are for charities or in very special circumstances.  I am truly sorry about this, but I think you would all rather I wrote books six and seven than spent my life signing books one to five.  So please, please, please do not send me your books for signature.  I no longer get to see the books that are being sent, which are returned to the sender.]]></c></r>
<r><c n="ID"><![CDATA[2]]></c><c n="a"><![CDATA[My publishers will forward letters.]]></c></r>
<r><c n="ID"><![CDATA[3]]></c><c n="a"><![CDATA[I have No Control Over Casting, I’m afraid.  Your best bet is to write to Warner Bros.]]></c></r>
<r><c n="ID"><![CDATA[4]]></c><c n="a"><![CDATA[The books have been planned for so long that there isn't room for any more ideas!  Fan fiction is really fun, though, and I am so proud to think that Harry Potter inspired so much creativity!]]></c></r>
	<?php if($website_version > 0 ){?>
<r><c n="ID"><![CDATA[78]]></c><c n="a"><![CDATA[TELL SOMEONE, whether it is your Mum, Dad, Aunt, Uncle, a teacher, a brother, a sister, an adult friend – just tell someone.  If the first person you tell doesn't seem to understand how bad the problem is, tell somebody else.  I know that it is very hard to admit that you are being bullied, but it is absolutely crucial if you are to end the misery.  Life in school can be very tough and any adult who has forgotten that is an idiot, so don't be ashamed... just tell.]]></c></r>
<r><c n="ID"><![CDATA[79]]></c><c n="a"><![CDATA[I don't know, you'll have to contact Warner Brothers!  (Their site is accessible through my 'Links' section).  I have no power over things like this, I'm afraid.]]></c></r>
<r><c n="ID"><![CDATA[80]]></c><c n="a"><![CDATA[I'm really not sure what you mean by 'middlemen'.  Most authors have agents whose job it is to negotiate contracts for them (authors not necessarily being very good businesspeople) and while you do not have to have an agent, I would advise any novice to get one if they can.  Other than your agent, you deal with an editor and perhaps the people marketing your book.  None of these people can be described as 'middlemen', they are simply part of the process of being published.  Of course, if you would rather nobody else is involved, you can self-publish, but that has always sounded like an awful lot of hard work to me.]]></c></r></rs></x>
	<?php } ?>
<?php } ?>