<?php $lang = (isset($_GET['lang']))? $_GET['lang'] : ""; 
$website_version = (file_exists("../config.ini"))?(parse_ini_file("../config.ini")["website_version"]):"4"; ?>

<?php if($lang == "fr" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[80]]></c><c n="q"><![CDATA[Comment éviter les intermédiaires lorsque l'on cherche à publier un livre ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[79]]></c><c n="q"><![CDATA[Pourrais-je rencontrer les acteurs des films de Harry Potter ou visiter les lieux de tournage ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[78]]></c><c n="q"><![CDATA[Quel conseil donneriez-vous aux enfants qui se font brutaliser ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[4]]></c><c n="q"><![CDATA[Utiliseriez-vous certaines de mes idées pour les prochaines aventures de Harry Potter ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="q"><![CDATA[Pourrais-je avoir un rôle ou une figuration dans le film ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="q"><![CDATA[À quelle adresse puis-je vous écrire ?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="q"><![CDATA[Puis-je espérer une dédicace ?]]></c><c n="sp"><![CDATA[0]]></c></r></rs></x>
<?php } elseif($lang == "es" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[80]]></c><c n="q"><![CDATA[¿Cómo se puede evitar a los intermediarios cuando intentas publicar un libro?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[79]]></c><c n="q"><![CDATA[¿Puedo conocer a los actores de las películas de Harry Potter o visitar el estudio?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[78]]></c><c n="q"><![CDATA[¿Cuál es tu consejo a los niños que sufren vejaciones en la escuela?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[4]]></c><c n="q"><![CDATA[¿Podrías utilizar alguna de mis ideas en el próximo libro de Harry Potter?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="q"><![CDATA[¿Puedo salir en la película?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="q"><![CDATA[¿A qué dirección puedo escribirte?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="q"><![CDATA[¿Puedes firmarme un libro?]]></c><c n="sp"><![CDATA[0]]></c></r></rs></x>
<?php } elseif($lang == "de" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[80]]></c><c n="q"><![CDATA[Wie lassen sich die Mittelsmänner vermeiden, wenn man versucht, ein Buch zu veröffentlichen?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[79]]></c><c n="q"><![CDATA[Kann ich die Mitwirkenden der Harry-Potter-Filme kennen lernen/den Drehort besichtigen?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[78]]></c><c n="q"><![CDATA[Welchen Rat können Sie Kindern geben, die von anderen schikaniert werden?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[4]]></c><c n="q"><![CDATA[Werden Sie einige meiner Ideen im nächsten Harry Potter-Buch verwenden?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="q"><![CDATA[Kann ich nicht im Film mitmachen?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="q"><![CDATA[Wohin kann ich Ihnen schreiben?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="q"><![CDATA[Könnten Sie bitte mein Buch signieren?]]></c><c n="sp"><![CDATA[0]]></c></r></rs></x>
<?php } elseif($lang == "it" ){?>
<x><rs n="faq" c="ID,q,sp,a"><r><c n="ID"><![CDATA[80]]></c><c n="q"><![CDATA[Come si possono evitare gli intermediari quando si cerca di pubblicare un libro?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[79]]></c><c n="q"><![CDATA[Posso conoscere il cast dei film di Harry Potter e visitare il set?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[78]]></c><c n="q"><![CDATA[Che consigli puoi dare ai bambini che subiscono prepotenze?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[4]]></c><c n="q"><![CDATA[Userai qualcuna delle mie idee nel prossimo libro di Harry Potter?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="q"><![CDATA[Posso far parte dei film?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="q"><![CDATA[A che indirizzo posso scriverti?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="q"><![CDATA[Firmeresti il mio libro?]]></c><c n="sp"><![CDATA[0]]></c></r></rs></x>
<?php } else {?>
<x><rs n="faq" c="ID,q,sp,a">
	<?php if($website_version > 0 ){?>
<r><c n="ID"><![CDATA[80]]></c><c n="q"><![CDATA[How can we avoid the middlemen when trying to publish a book?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[79]]></c><c n="q"><![CDATA[Can I meet the cast of the Harry Potter films/visit the set?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[78]]></c><c n="q"><![CDATA[What is your advice to children who are being bullied?]]></c><c n="sp"><![CDATA[0]]></c></r>
	<?php } ?>
<r><c n="ID"><![CDATA[4]]></c><c n="q"><![CDATA[Will you use some of my ideas in the next Harry Potter book?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[3]]></c><c n="q"><![CDATA[Can I be in the film?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[2]]></c><c n="q"><![CDATA[Where can I write to you?]]></c><c n="sp"><![CDATA[0]]></c></r><r><c n="ID"><![CDATA[1]]></c><c n="q"><![CDATA[Will you sign my book?]]></c><c n="sp"><![CDATA[0]]></c></r></rs></x>
<?php } ?>